site_name: EA Powertools Governed Metrics Service
pages:
- Home: 'index.md'
- Introduction: 'user-guide/intro.md'
- Installation:
    - 'Governed Metrics Service Prerequisites' : 'user-guide/prereqs.md'
    - 'Installing GMS' : 'user-guide/install.md'
- Configuration:
    - 'Metrics Library App' : 'user-guide/app.md'
    - 'QMC Configuration' : 'user-guide/qmc.md'
- User-Guide: 
    - 'Testing Goverened Metrics Service' : 'user-guide/interface.md'
    - 'GMS Example' : 'user-guide/validation.md'
- Governed Metrics Service API: 'gmsapi.md'
- Uninstall: 'user-guide/uninstall.md'
- About: 'about.md'
theme: readthedocs
